# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: ["docs/**"]
  pull_request:
    branches: [ "main" ]
    paths-ignore: ["docs/**"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "microsoft"
        cache: "sbt"
    - name: Run tests
      run: sbt test coverageReport
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Fake deploy
      run: echo Not actually deploying...
